### ISSUE TITLE
Make MCP23s17 reset pin optional

### ISSUE THREAD

**Issue by thijstriemstra** [wollewald/MCP23017_WE#16]
There is no optional reset pin for the mcp23s17 like there is for the mcp23017 (#4).

Supplying `-1` throws this errors:

```
[    27][E][esp32-hal-gpio.c:95] __pinMode(): Invalid pin selected
E (24) gpio: gpio_set_level(226): GPIO output gpio_num error
E (25) gpio: gpio_set_level(226): GPIO output gpio_num error
E (39) gpio: gpio_set_level(226): GPIO output gpio_num error
```

Passing an unused pin, e.g. 27 in my case, seems to work.

**Comment by wollewald** [comment]
The reset pin of the mcp23s17 is pin no 18. The reset pin is only used in init() to ensure that all registers are set to default if you upload a new sketch without disconnecting from power. What I have implemented a week ago and not yet documented is a software reset. If you pass a reset pin with a number >= 99 the software reset will carried out instead of the hardware reset. Like this:
````
#define RESET_PIN 99
#define MCP_ADDRESS 0x20 // (A2/A1/A0 = LOW)
MCP23S17 myMCP = MCP23S17(CS_PIN, RESET_PIN, MCP_ADDRESS);
````
The software reset just sets all registers to default values by SPI/I2C commands. 
If you don't connect the reset pin to a real pin, then you should connect it to HIGH level.

**Comment by thijstriemstra** [comment]
Thanks for the feedback. An additional mcp23s17 constructor where reset_pin = 99 would be nice. Tested with 99 (instead of 27) and everything seems to work ok.

**Comment by wollewald** [comment]
If you don't pass the reset pin, 99 will be applied now.
